import { jStat } from 'jstat';
import {metrics,proxies} from './catalog';
import type {SurveyRecord,Filters} from './types';
export const defaultFilters:Filters={provider:'both',tenure:[],services:[],support:'all',failure:'all',switching:'all'};
export const mean=(x:number[])=>x.length?x.reduce((s,v)=>s+v,0)/x.length:null;
export function quantile(sorted:number[],p:number){if(!sorted.length)return null;const i=(sorted.length-1)*p,lo=Math.floor(i);return sorted[lo]+(sorted[Math.ceil(i)]-sorted[lo])*(i-lo)}
export function summary(x:number[]){const sorted=[...x].sort((a,b)=>a-b),m=mean(x),counts=[1,2,3,4,5].map(v=>x.filter(n=>n===v).length),variance=x.length>1?x.reduce((s,v)=>s+(v-m!)**2,0)/(x.length-1):null;return {n:x.length,mean:m,median:quantile(sorted,.5),modes:x.length?counts.flatMap((c,i)=>c===Math.max(...counts)?[i+1]:[]):[],counts,proportions:counts.map(c=>x.length?c/x.length:null),sd:variance===null?null:Math.sqrt(variance),variance};}
export function filterRecords(rows:SurveyRecord[],f:Filters){return rows.filter(r=>(f.provider==='both'||r.provider===f.provider)&&(!f.tenure.length||f.tenure.includes(r.tenure))&&(!f.services.length||f.services.some(s=>r.services.includes(s)))&&(['support','failure','switching'] as const).every(k=>f[k]==='all'||r[k]===(f[k]==='yes')))}
export function eligible(r:SurveyRecord,id:string){const m=metrics.find(m=>m.id===id);return !!m&&(m.population==='all'||r[m.population])&&Number.isFinite(r.ratings[id]);}
export function values(rows:SurveyRecord[],id:string,provider?:string){return rows.filter(r=>(!provider||r.provider===provider)&&eligible(r,id)).map(r=>r.ratings[id]!)}
export function ranks(x:number[]){const order=x.map((v,i)=>({v,i})).sort((a,b)=>a.v-b.v),r=Array(x.length).fill(0);let tie=0;for(let i=0;i<order.length;){let j=i+1;while(j<order.length&&order[j].v===order[i].v)j++;for(let k=i;k<j;k++)r[order[k].i]=(i+1+j)/2;tie+=(j-i)**3-(j-i);i=j;}return {r,tie};}
export function mannWhitney(a:number[],b:number[]){if(!a.length||!b.length)return {u:null,p:null,cliffsDelta:null};const n=a.length+b.length,{r,tie}=ranks([...a,...b]),u=r.slice(0,a.length).reduce((s,v)=>s+v,0)-a.length*(a.length+1)/2,variance=a.length*b.length/12*(n+1-tie/(n*(n-1))),z=variance>0?Math.max(0,Math.abs(u-a.length*b.length/2)-.5)/Math.sqrt(variance):0;return {u,p:variance>0?Math.min(1,2*(1-jStat.normal.cdf(z,0,1))):null,cliffsDelta:2*u/(a.length*b.length)-1};}
export function pearson(a:number[],b:number[]){if(a.length<2||a.length!==b.length)return null;const ma=mean(a)!,mb=mean(b)!,cov=a.reduce((s,v,i)=>s+(v-ma)*(b[i]-mb),0),den=Math.sqrt(a.reduce((s,v)=>s+(v-ma)**2,0)*b.reduce((s,v)=>s+(v-mb)**2,0));return den?cov/den:null;}
export const spearman=(a:number[],b:number[])=>pearson(ranks(a).r,ranks(b).r);
export function alpha(items:number[][]){if(items.length<2||!items[0]||items[0].length<2)return null;const k=items[0].length,vs=Array.from({length:k},(_,i)=>summary(items.map(r=>r[i])).variance!),total=summary(items.map(r=>r.reduce((s,v)=>s+v,0))).variance;return total?k/(k-1)*(1-vs.reduce((s,v)=>s+v,0)/total):null;}
export function holm(ps:Record<string,number>,familySize=Object.keys(ps).length){const sorted=Object.entries(ps).sort((a,b)=>a[1]-b[1]);let prev=0;return Object.fromEntries(sorted.map(([key,p],i)=>{prev=Math.max(prev,Math.min(1,p*(familySize-i)));return [key,prev]}));}
export function compare(rows:SurveyRecord[],id:string){const a=values(rows,id,'Airtel'),b=values(rows,id,'Jio'),A=summary(a),J=summary(b),raw=mannWhitney(a,b),canInfer=a.length>=20&&b.length>=20&&raw.p!==null;let reason='';if(!a.length||!b.length)reason='Both providers need eligible responses for a comparison.';else if(raw.p===null)reason='All eligible ratings are identical; rank variance is zero.';else if(!canInfer)reason='At least 20 eligible records per provider are required for this exploratory test.';const family:Record<string,number>={};for(const key of proxies){const aa=values(rows,key,'Airtel'),bb=values(rows,key,'Jio');const p=mannWhitney(aa,bb).p;if(aa.length>=20&&bb.length>=20&&p!==null)family[key]=p;}return {id,A,J,...raw,p:canInfer?raw.p:null,adjustedP:canInfer?holm(family,5)[id]??null:null,meanDifference:A.mean!==null&&J.mean!==null?A.mean-J.mean:null,canInfer,reason};}
export function chiSquare(table:number[][]){const n=table.flat().reduce((s,v)=>s+v,0);if(table.length<2||!table[0]||table[0].length<2||!n)return {statistic:null,p:null,v:null,expected:[],reason:'A nonempty two-way table is required.'};const rs=table.map(r=>r.reduce((s,v)=>s+v,0)),cs=table[0].map((_,i)=>table.reduce((s,r)=>s+r[i],0)),expected=rs.map(r=>cs.map(c=>r*c/n));if(expected.flat().some(v=>v<5))return {statistic:null,p:null,v:null,expected,reason:'Every expected cell must contain at least 5 records.'};if(rs.some(n=>n<20))return {statistic:null,p:null,v:null,expected,reason:'At least 20 eligible respondents per provider are required for inference.'};const statistic=table.reduce((s,row,i)=>s+row.reduce((sum,v,j)=>sum+(v-expected[i][j])**2/expected[i][j],0),0),df=(table.length-1)*(table[0].length-1);return {statistic,p:1-jStat.chisquare.cdf(statistic,df),v:Math.sqrt(statistic/(n*Math.min(table.length-1,table[0].length-1))),expected,reason:''};}
export function rng(seed:number){return ()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return ((t^t>>>14)>>>0)/4294967296;};}
export function seedFrom(s:string){let seed=2166136261;for(let i=0;i<s.length;i++)seed=Math.imul(seed^s.charCodeAt(i),16777619);return seed>>>0;}
export function bootstrap(a:number[],b:number[],seed=20260909,count=2000){if(a.length<20||b.length<20)return null;const random=rng(seed),d=[];for(let k=0;k<count;k++){let am=0,bm=0;for(let i=0;i<a.length;i++)am+=a[Math.floor(random()*a.length)];for(let i=0;i<b.length;i++)bm+=b[Math.floor(random()*b.length)];d.push(am/a.length-bm/b.length);}d.sort((a,b)=>a-b);return [quantile(d,.025)!,quantile(d,.975)!];}
export function permutation(a:number[],b:number[],seed=20260909,count=4999){const ar=ranks(a).r,br=ranks(b).r,observed=pearson(ar,br);if(observed===null||a.length<20)return {rho:observed,p:null};const random=rng(seed);let extreme=0;for(let k=0;k<count;k++){const y=[...br];for(let i=y.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[y[i],y[j]]=[y[j],y[i]];}if(Math.abs(pearson(ar,y)!)>=Math.abs(observed)-1e-12)extreme++;}return {rho:observed,p:(extreme+1)/(count+1)};}
export function interpret(result:ReturnType<typeof compare>,label:string){const {A,J,meanDifference:d}=result;if(!A.n&&!J.n)return `No eligible responses remain for ${label.toLowerCase()}. Broaden the filters to examine this question.`;if(d===null)return `${A.n?'Airtel':'Jio'} has ${A.n||J.n} eligible responses in this segment. Select both providers to estimate a difference. A single-provider view cannot establish comparative advantage.`;const direction=d>=0?'above':'below',test=result.adjustedP??result.p;return `Airtel’s mean ${label.toLowerCase()} rating is ${Math.abs(d).toFixed(2)} points ${direction} Jio’s on the 1–5 scale (n = ${A.n} / ${J.n}). ${!result.canInfer?result.reason:test!==null&&test<.05?'The distributions show evidence of a difference under the stated exploratory test. Its operational importance still needs context.':'There is no clear evidence of a distribution difference under this exploratory test; that does not establish equivalence.'} Read the response distribution alongside the mean. These filtered associations cannot establish cause or population-wide preference.`;}
