'use client';
import AppLink from '@/components/AppLink';


import {usePathname} from 'next/navigation';
import {useEffect,useRef,useState} from 'react';
import {MotionEnvironment,MotionToggle} from './Signal';
import {chapters,reportPages,studioPages,evidencePages} from '@/lib/catalog';
import {Arrow} from './ui';
export default function Shell({children,studio=false}:{children:React.ReactNode;studio?:boolean}){const pathname=usePathname();const path=pathname.endsWith('/')?pathname:pathname+'/';const evidence=path==='/methodology/'||path==='/sources/';const [open,setOpen]=useState(false);const dialog=useRef<HTMLDialogElement>(null);const current=reportPages.findIndex(p=>p[0]===path);useEffect(()=>{setOpen(false);dialog.current?.close()},[path]);useEffect(()=>{if(open)dialog.current?.showModal();else dialog.current?.close()},[open]);const nav=<><div className="rail-heading">{studio?'The analytical workspace':evidence?'The evidence register':'The report'}</div>{studio?<nav aria-label="Studio views">{studioPages.map(([url,label],i)=><AppLink className={path===url?'active':''} href={url} key={url} aria-current={path===url?'page':undefined}><span>{String(i+1).padStart(2,'0')}</span>{label}</AppLink>)}</nav>:evidence?<nav aria-label="Evidence pages">{evidencePages.map(([url,label])=><AppLink className={path===url?'active':''} href={url} key={url}>{label}</AppLink>)}</nav>:<nav aria-label="Report chapters">{chapters.map(c=><div className="nav-group" key={c.group}><p>{c.group}</p>{c.items.map(([url,label,num])=><AppLink className={path===url?'active':''} href={url} key={url} aria-current={path===url?'page':undefined}><span>{num}</span>{label}</AppLink>)}</div>)}</nav>}<div className="rail-note"><span className="tiny-mark" aria-hidden="true"/><p>Two service architectures.<br/>Different execution risks.</p><span>ACADEMIC STUDY · 2026</span></div></>;
return <MotionEnvironment><AppLink className="skip-link" href="#main">Skip to content</AppLink><header className="topbar"><AppLink className="wordmark" href="/"><span className="brand-symbol" aria-hidden="true"><i/><i/></span><span>Airtel <b>×</b> Jio<small>THE LIVING SIGNAL</small></span></AppLink><nav className="topnav" aria-label="Main navigation"><AppLink className={!studio&&!evidence?'selected':''} href="/">Report</AppLink><AppLink className={studio?'selected':''} href="/studio/">Studio <span className="studio-dot" aria-hidden="true"/></AppLink><AppLink className={evidence?'selected':''} href="/methodology/">Evidence</AppLink></nav><MotionToggle/><div className="edition">GROUP 06<span>SEPTEMBER 2026</span></div><button className="mobile-menu" aria-label="Open chapter navigation" onClick={()=>setOpen(true)}>☰</button></header><div className={`workspace ${path==='/'?'home-workspace':''} ${studio?'studio-workspace':''}`}><aside className="rail">{nav}</aside><dialog className="nav-dialog" ref={dialog} onCancel={()=>setOpen(false)} onClick={e=>{if(e.target===dialog.current)setOpen(false)}}><button className="close-dialog" onClick={()=>setOpen(false)}>Close ×</button>{nav}</dialog><main id="main" className="main" tabIndex={-1}><div className="page-enter" key={path}>{children}</div>{current>=0&&<nav className="chapter-pagination" aria-label="Adjacent chapters">{current>0?<AppLink href={reportPages[current-1][0]}><small>PREVIOUS</small>← {reportPages[current-1][1]}</AppLink>:<div/>}{current<reportPages.length-1?<AppLink href={reportPages[current+1][0]}><small>NEXT CHAPTER · {reportPages[current+1][2]}</small>{reportPages[current+1][1]} <Arrow/></AppLink>:<AppLink href="/studio/"><small>KEEP EXPLORING</small>Enter Studio <Arrow/></AppLink>}</nav>}<footer className="footer"><span>Alliance School of Business · Group 6</span><AppLink href="/methodology/">Methods & limitations <Arrow diagonal/></AppLink></footer></main></div></MotionEnvironment>}
