import {chromium,expect} from '@playwright/test';
import {readFile,writeFile} from 'node:fs/promises';
const records=JSON.parse(await readFile('public/data/survey.json','utf8'));
const browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
const origin='http://127.0.0.1:4173';await page.goto(origin+'/studio/',{waitUntil:'networkidle'});await page.locator('.echart svg').waitFor();const svg=await page.locator('.echart svg').elementHandle();let checks=0;
for(const provider of ['Airtel','Jio','both']){await page.getByLabel('Provider',{exact:true}).selectOption(provider);await expect(page.locator('[class*="sampleLens"] strong')).toHaveText(`${provider==='both'?946:records.filter(r=>r.provider===provider).length} / 946 records`);checks++}
if(!await svg.evaluate(el=>el.isConnected))throw Error('Chart was recreated when filters changed');
for(const [key,label] of [['support','Support contact'],['failure','Significant failure'],['switching','Considered switching']]){for(const value of ['yes','no','all']){await page.getByLabel(label,{exact:true}).selectOption(value);const n=records.filter(r=>value==='all'||r[key]===(value==='yes')).length;await expect(page.locator('[class*="sampleLens"] strong')).toHaveText(`${n} / 946 records`);checks++}}
for(const [key,label,items] of [['tenure','Customer tenure',['<1 Year','1 - 3 Years','3 - 5 Years','> 5 Years']],['services','Reported services',['Prepaid','Postpaid','Fiber Broadband','DTH Service']]]){const filter=page.locator('.multi-filter').filter({has:page.locator('summary').filter({hasText:label})});await filter.locator('summary').click();for(const item of items){await filter.getByLabel(item,{exact:true}).check();const n=records.filter(r=>key==='services'?r.services.includes(item):r.tenure===item).length;await expect(page.locator('[class*="sampleLens"] strong')).toHaveText(`${n} / 946 records`);await filter.getByLabel(item,{exact:true}).uncheck();checks++}await filter.getByLabel(items[0],{exact:true}).check();await filter.getByLabel(items[1],{exact:true}).check();await page.getByLabel('Provider',{exact:true}).selectOption('Airtel');const n=records.filter(r=>r.provider==='Airtel'&&(key==='services'?r.services.some(s=>items.slice(0,2).includes(s)):items.slice(0,2).includes(r.tenure))).length;await expect(page.locator('[class*="sampleLens"] strong')).toHaveText(`${n} / 946 records`);checks++;await page.getByRole('button',{name:'Reset filters'}).click();await filter.locator('summary').click()}
await page.getByLabel('Provider',{exact:true}).selectOption('Jio');await page.getByLabel('Provider',{exact:true}).selectOption('Airtel');await page.goBack();await expect(page.getByLabel('Provider',{exact:true})).toHaveValue('Jio');checks++;
for(const value of ['response','digital','coverage','promise'])await page.getByLabel('Question',{exact:true}).selectOption(value);await expect(page.locator('.chart-heading h2')).toContainText(/[Pp]romise/);await page.waitForTimeout(700);await expect(page.locator('.inference')).not.toContainText('Calculating');checks++;
await page.goto(origin+'/',{waitUntil:'networkidle'});const packet=page.locator('path[class*="signalPacket"]').first();const before=await packet.evaluate(el=>getComputedStyle(el).strokeDashoffset);await page.waitForTimeout(250);const after=await packet.evaluate(el=>getComputedStyle(el).strokeDashoffset);if(before===after)throw Error('The signal does not move');checks++;
await page.getByRole('button',{name:'Trace the signal'}).click();await expect(page.getByRole('button',{name:'02 delivery'})).toHaveAttribute('aria-pressed','true',{timeout:4000});await page.getByRole('button',{name:'Pause motion',exact:true}).click();const paused=await packet.evaluate(el=>getComputedStyle(el).strokeDashoffset);await page.waitForTimeout(150);if(paused!==await packet.evaluate(el=>getComputedStyle(el).strokeDashoffset))throw Error('Pause did not stop the signal');await page.getByRole('button',{name:'Resume motion',exact:true}).click();checks++;
await page.goto(origin+'/journeys/mobile/',{waitUntil:'networkidle'});await page.getByRole('button',{name:'Play journey'}).click();await expect(page.locator('.journey-stages>button').nth(1)).toHaveAttribute('aria-pressed','true',{timeout:4000});checks++;
await page.emulateMedia({reducedMotion:'reduce'});await page.reload({waitUntil:'networkidle'});await expect(page.getByRole('button',{name:'Play journey'})).toBeDisabled();await page.locator('.journey-stages>button').nth(2).focus();await page.keyboard.press('Enter');await expect(page.locator('.journey-stages>button').nth(2)).toHaveAttribute('aria-pressed','true');checks++;
// A 1440px physical viewport at 200% browser zoom has 720 CSS pixels.
// CSS `zoom` is unsuitable here: unlike browser zoom it leaves media queries unchanged.
const zoomContext=await browser.newContext({viewport:{width:720,height:500},deviceScaleFactor:2,reducedMotion:'reduce'});const zoomPage=await zoomContext.newPage();await zoomPage.goto(origin+'/studio/',{waitUntil:'networkidle'});const overflow=await zoomPage.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);if(overflow)throw Error('200% equivalent reflow overflow');await zoomContext.close();
await writeFile('test-results/interaction-depth.json',JSON.stringify({checks,chartPreserved:true,motionVerified:true,reducedMotion:true,zoom200Percent:true,errors},null,2));await browser.close();if(errors.length)throw Error(errors.join('\n'));console.log(JSON.stringify({checks,errors}));
