import lighthouse from 'lighthouse';
import {chromium} from '@playwright/test';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {cpus,platform} from 'node:os';
import {gzipSync} from 'node:zlib';
const origin='http://127.0.0.1:4173';await mkdir('test-results/performance',{recursive:true});
const chrome=await chromium.launch({headless:true,args:['--remote-debugging-port=9227']});const reports=[];
try{for(const route of ['/','/studio/','/studio/text/']){const result=await lighthouse(origin+route,{port:9227,output:'json',logLevel:'error',onlyCategories:['performance','accessibility','best-practices','seo']});const lhr=result.lhr;reports.push({route,scores:Object.fromEntries(Object.entries(lhr.categories).map(([k,v])=>[k,Math.round(v.score*100)])),metrics:Object.fromEntries(['first-contentful-paint','largest-contentful-paint','total-blocking-time','cumulative-layout-shift','speed-index'].map(k=>[k,lhr.audits[k].displayValue])),deductions:Object.values(lhr.audits).filter(a=>a.score!==null&&a.score<1&&a.details?.type!=='opportunity').map(a=>({id:a.id,title:a.title,score:a.score}))});await writeFile('test-results/performance/'+(route==='/'?'home':route.replaceAll('/','-'))+'.json',result.report);console.log(JSON.stringify(reports.at(-1)));}}finally{await chrome.close()}
const browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}});const page=await context.newPage();const transfer=[];
for(const route of ['/','/studio/','/studio/text/']){const scripts=new Set();const response=r=>{if(r.request().resourceType()==='script'&&r.url().startsWith(origin))scripts.add(new URL(r.url()).pathname)};page.on('response',response);await page.goto(origin+route,{waitUntil:'networkidle'});if(route.startsWith('/studio'))await page.locator('[class*="sampleLens"]').waitFor();await page.waitForTimeout(1000);let gzip=0;for(const file of scripts)gzip+=gzipSync(await readFile('out'+decodeURIComponent(file))).length;transfer.push({route,scriptCount:scripts.size,javascriptGzipBytes:gzip});page.off('response',response)}
await page.goto(origin+'/studio/',{waitUntil:'networkidle'});await page.locator('.chart-legend').waitFor();const latencies=[];
for(let i=0;i<25;i++){const provider=i%2?'Jio':'Airtel';const latency=await page.evaluate(async provider=>{const selector=document.querySelector('select[aria-label="Provider"]');const target=provider==='Airtel'?'433':'513';const start=performance.now();const result=new Promise(resolve=>{const observer=new MutationObserver(()=>{const lens=document.querySelector('[class*="sampleLens"] strong');const chart=document.querySelector('.chart-legend');if(lens?.textContent?.startsWith(target)&&chart?.textContent?.includes('n = '+target)){observer.disconnect();resolve(performance.now()-start)}});observer.observe(document.querySelector('main'),{childList:true,characterData:true,subtree:true});setTimeout(()=>{observer.disconnect();resolve(1000)},1000)});selector.value=provider;selector.dispatchEvent(new Event('change',{bubbles:true}));return result},provider);latencies.push(latency)}
await browser.close();latencies.sort((a,b)=>a-b);const summary={device:{cpu:cpus()[0].model,platform:platform(),node:process.version,browser:'Playwright Chromium',lighthouse:'mobile simulated throttling'},reports,transfer,filterLatencyMs:{n:latencies.length,median:latencies[Math.floor(latencies.length/2)],p95:latencies[Math.ceil(latencies.length*.95)-1],maximum:latencies.at(-1)},note:'Noindex is intentional for this academic preview; the is-crawlable SEO deduction is recorded separately.'};await writeFile('test-results/performance/summary.json',JSON.stringify(summary,null,2));console.log(JSON.stringify({transfer,filterLatencyMs:summary.filterLatencyMs}));
