import {chromium,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {mkdir,writeFile} from 'node:fs/promises';
const routes=['/','/research-design/','/operator-profiles/','/market-position/','/7ps/commercial/','/7ps/delivery/','/7ps/controls/','/servqual/','/network-evidence/','/gap-model/','/journeys/mobile/','/journeys/billing-and-home/','/service-recovery/','/roadmap/','/conclusion/','/methodology/','/sources/','/studio/','/studio/ratings/','/studio/recovery/','/studio/retention/','/studio/relationships/','/studio/text/','/studio/quality/'];
await mkdir('test-results/screens',{recursive:true});
const browser=await chromium.launch({headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
const page=await context.newPage();
const errors=[],requests=[],results=[];
page.on('pageerror',e=>errors.push(String(e)));
page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
page.on('response',r=>{if(r.status()>=400)requests.push({url:r.url(),status:r.status()})});
const name=r=>r==='/'?'home':r.split('/').filter(Boolean).join('-');
for(const route of routes){const response=await page.goto('http://127.0.0.1:4173'+route,{waitUntil:'networkidle'});await page.locator('h1').waitFor();if(route.startsWith('/studio'))await page.locator('.sample-counts').waitFor();if(route==='/studio/text/')await page.locator('.theme-matrix').waitFor();await page.waitForTimeout(150);const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);const accessibility=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze();results.push({route,status:response.status(),overflow,violations:accessibility.violations.map(v=>({id:v.id,impact:v.impact,count:v.nodes.length,examples:v.nodes.slice(0,3).map(n=>({target:n.target,summary:n.failureSummary}))}))});await page.screenshot({path:`test-results/screens/${name(route)}.png`,fullPage:true});console.log(JSON.stringify({route,overflow,violations:results.at(-1).violations.map(v=>`${v.id}:${v.count}`)}));}
await writeFile('test-results/routes.json',JSON.stringify({results,errors,requests},null,2));
const responsive=[];
for(const width of [360,390,768,1024,1440,1920]){await page.setViewportSize({width,height:900});for(const route of ['/','/gap-model/','/journeys/mobile/','/roadmap/','/studio/','/studio/text/']){await page.goto('http://127.0.0.1:4173'+route,{waitUntil:'networkidle'});if(route==='/studio/text/')await page.locator('.theme-matrix').waitFor();const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);responsive.push({width,route,overflow});if(width===390)await page.screenshot({path:`test-results/screens/${name(route)}-mobile.png`,fullPage:true});}}
await writeFile('test-results/responsive.json',JSON.stringify(responsive,null,2));
await page.setViewportSize({width:1440,height:1000});
await page.goto('http://127.0.0.1:4173/studio/',{waitUntil:'networkidle'});
await expect(page.locator('.inference')).not.toContainText('Calculating…',{timeout:15000});
await expect(page.locator('.inference')).not.toContainText('Background calculations are unavailable');
const filterPanel=page.locator('.filter-panel');
await filterPanel.getByLabel('Provider',{exact:true}).selectOption('Airtel');
await expect(page.locator('.sample-counts')).toContainText('433');
await expect(page.locator('.interpretation-copy')).toContainText('Select both providers');
await filterPanel.getByRole('button',{name:'Reset filters'}).click();
await filterPanel.getByLabel('Support contact',{exact:true}).selectOption('no');
await page.getByLabel('Question',{exact:true}).selectOption('response');
await expect(page.locator('.chart-panel')).toContainText('No eligible answers');
await filterPanel.getByRole('button',{name:'Reset filters'}).click();
await expect(page.locator('.chart-legend')).toContainText('271');
await expect(page.locator('.chart-legend')).toContainText('328');
await page.getByRole('button',{name:'Rating 4',exact:true}).click();
await expect(page.locator('.interpretation-copy')).toContainText('Rating 4');
await page.getByLabel('Question',{exact:true}).selectOption('digital');
await expect(page.locator('.interpretation-copy')).not.toContainText('Rating 4:');
await page.reload({waitUntil:'networkidle'});await expect(page.getByLabel('Question',{exact:true})).toHaveValue('digital');
await page.goto('http://127.0.0.1:4173/studio/relationships/',{waitUntil:'networkidle'});
await expect(page.locator('.interpretation-panel')).not.toContainText('Calculating…',{timeout:20000});
await expect(page.locator('.interpretation-panel')).toContainText('0.231');
await page.getByLabel('Second rating',{exact:true}).selectOption('reliability');
await expect(page.locator('.interpretation-panel')).toContainText('perfectly correlated with itself');
await page.goto('http://127.0.0.1:4173/studio/text/',{waitUntil:'networkidle'});await page.locator('.theme-matrix').waitFor();
await expect(page.locator('.notice')).toContainText('Sentiment withheld');
await page.getByLabel('Question',{exact:true}).selectOption('improvement');
await page.getByLabel('Weighting',{exact:true}).selectOption('unique');
await expect(page.locator('.text-summary')).toContainText('609');
await page.locator('.phrase-panel button').first().click();
await expect(page.locator('.response-list article').first()).toBeVisible();
await page.getByRole('button',{name:'Clear text selection'}).click();
await page.getByLabel('Search response text').fill('impossiblematchxyzz');
await expect(page.locator('.responses')).toContainText('No text matches');
for(const route of ['/research-design/','/7ps/commercial/','/7ps/delivery/','/servqual/','/gap-model/','/journeys/mobile/','/service-recovery/','/roadmap/']){await page.goto('http://127.0.0.1:4173'+route,{waitUntil:'networkidle'});const buttons=page.locator('main button[aria-pressed]:not(:disabled)');for(let i=0;i<await buttons.count();i++){await buttons.nth(i).click();await expect(buttons.nth(i)).toHaveAttribute('aria-pressed','true');}}
await page.setViewportSize({width:390,height:900});await page.goto('http://127.0.0.1:4173/',{waitUntil:'networkidle'});await page.getByRole('button',{name:'Open chapter navigation'}).click();await expect(page.locator('dialog')).toBeVisible();await page.keyboard.press('Escape');await expect(page.locator('dialog')).not.toBeVisible();
await page.setViewportSize({width:1440,height:1000});await page.goto('http://127.0.0.1:4173/studio/',{waitUntil:'networkidle'});await page.evaluate(()=>document.documentElement.style.fontSize='200%');const zoomOverflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);
await writeFile('test-results/interactions.json',JSON.stringify({passed:true,zoomOverflow,errors,requests},null,2));
await browser.close();
console.log(JSON.stringify({routeCount:results.length,accessibilityViolations:results.reduce((n,r)=>n+r.violations.length,0),responsiveOverflows:responsive.filter(r=>r.overflow),zoomOverflow,errors,requests},null,2));
